### ISSUE TITLE
Ironically blocked by Cloudflare

### ISSUE THREAD

**Issue by james-darkfox** [privacypass/challenge-bypass-extension#101]
Can an administrator of the https://captcha.website/ service please enable Cloudflare's Onion Service in the crypto tab?

https://blog.cloudflare.com/cloudflare-onion-service/

**Comment by grittygrease** [comment]
Done.

**Comment by james-darkfox** [comment]
Thanks, and it was. Yet Cloudflare still decides to just captcha-wall it off. Enabling this usually fixes it.

*shrugs*

**Comment by james-darkfox** [comment]
@alxdavids Not resolved. Cloudflare still blocks it outright. There is some misconfiguration for captcha.website on Cloudflare. CF does support tor but its plethora of configuration options have edge cases that break services - especially APIs - which this isn't.

**Comment by XVicarious** [comment]
I get a message that says "Your computer or network is sending automated requests" or whatever when i try to use a pass on NameCheap (with a Cloudflare page), but it goes through when I solve the captcha manually.
